@echo off
setlocal enabledelayedexpansion

:: ============================================================================
::  compile.bat  —  Groovy MiSTer MP4 Player
::  Adapted from mpeg2fpga-master\compile.bat
::
::  Usage:
::    compile.bat                  — full compile, prompts for release desc
::    compile.bat "phase1_fifo"    — full compile + auto-release with that desc
::    compile.bat skip             — full compile, no release prompt
::
::  Requires: Quartus Prime Lite 17.0.2  (same toolchain as the .qpf)
::
::  WHY the explicit build_id step exists:
::    Groovy.sv line 238 does `include "build_id.v"`.  Quartus resolves
::    `include directives during Analysis & Synthesis, BEFORE the Tcl
::    PRE_FLOW_SCRIPT_FILE hook has a chance to create the file.  So
::    build_id.v must be generated by a standalone quartus_sh call that
::    runs before quartus_map.  clean.bat deletes it, making this step
::    mandatory on every fresh build.
:: ============================================================================

set "DESC=%~1"

:: ---- Quartus 17.0 toolchain path ----
set "QUARTUS_BIN=C:\intelFPGA_lite\17.0\quartus\bin64"
set PATH=%QUARTUS_BIN%;%PATH%

:: ---- Project identity ----
set "PROJECT=Groovy"

echo.
echo ============================================================
echo   Groovy MiSTer MP4 Player  ^|  Quartus 17.0 Full Compile
echo ============================================================
echo.

:: ---- Git Auto-Commit: Save source changes before compile ----
echo [Git] Checking for uncommitted changes...
git diff-index --quiet HEAD --
if %errorlevel% neq 0 (
    echo [Git] Changes detected, creating auto-commit...

    :: Build timestamp for commit message
    for /f "tokens=2 delims==" %%I in ('wmic os get localdatetime /value 2^>nul') do set "_dt=%%I"
    set "TIMESTAMP=!_dt:~0,4!-!_dt:~4,2!-!_dt:~6,2! !_dt:~8,2!:!_dt:~10,2!:!_dt:~12,2!"

    :: Stage source files (not db/ artifacts - those are in .gitignore)
    git add -A

    :: Create commit with timestamp + optional description
    if "%DESC%"=="" (
        git commit -m "Auto-commit before compile - !TIMESTAMP!"
    ) else (
        git commit -m "Auto-commit: %DESC% - !TIMESTAMP!"
    )

    echo [Git] Commit created successfully
) else (
    echo [Git] No changes to commit
)
echo.

:: ---- Step 0: Generate build_id.v (date stamp used in the OSD version string) ----
::      build_id.tcl opens the project, reads the device/revision, closes it,
::      then writes build_id.v.  It is idempotent: re-running on the same date
::      leaves the file unchanged.
echo [0/4] Generating build_id.v  (quartus_sh) ...
quartus_sh -t sys/build_id.tcl %PROJECT% %PROJECT%
if %errorlevel% neq 0 (
    echo.
    echo ERROR: build_id.tcl failed. Is Groovy.qpf present in the current directory?
    exit /b %errorlevel%
)

:: ---- Step 1: Analysis ^& Synthesis ----
echo [1/4] Analysis ^& Synthesis  (quartus_map) ...
quartus_map %PROJECT%
if %errorlevel% neq 0 (
    echo.
    echo ERROR: quartus_map failed. Check output_files\%PROJECT%.map.rpt
    exit /b %errorlevel%
)

:: ---- Step 2: Fitter (Place ^& Route) ----
echo [2/4] Fitter (Place ^& Route)  (quartus_fit) ...
quartus_fit %PROJECT%
if %errorlevel% neq 0 (
    echo.
    echo ERROR: quartus_fit failed. Check output_files\%PROJECT%.fit.rpt
    exit /b %errorlevel%
)

:: ---- Step 3: Assembler  (generates SOF; GENERATE_RBF_FILE=ON also makes RBF) ----
echo [3/4] Assembler  (quartus_asm) ...
quartus_asm %PROJECT%
if %errorlevel% neq 0 (
    echo.
    echo ERROR: quartus_asm failed. Check output_files\%PROJECT%.asm.rpt
    exit /b %errorlevel%
)

:: ---- Step 4: Static Timing Analysis ----
echo [4/4] Static Timing Analysis  (quartus_sta) ...
quartus_sta %PROJECT%
if %errorlevel% neq 0 (
    echo.
    echo ERROR: quartus_sta failed. Check output_files\%PROJECT%.sta.rpt
    exit /b %errorlevel%
)

:: ---- Generate compressed RBF from SOF ----
::      The assembler already produced an uncompressed RBF (GENERATE_RBF_FILE=ON),
::      but MiSTer loads faster with bitstream compression.  This overwrites it.
echo.
echo Generating compressed RBF ...
quartus_cpf -c -o bitstream_compression=on output_files\%PROJECT%.sof output_files\%PROJECT%.rbf
if %errorlevel% neq 0 (
    echo.
    echo ERROR: quartus_cpf failed.
    exit /b %errorlevel%
)

echo.
echo ============================================================
echo   Compilation successful.
echo   Bitstream: output_files\%PROJECT%.rbf
echo ============================================================
echo.

:: ---- Optional release archive ----
if /i "%DESC%"=="skip" goto :done

if "%DESC%"=="" (
    set /p "DESC=Enter release description (or press Enter to skip, 'skip' to never prompt): "
)

if "!DESC!"=="" goto :done
if /i "!DESC!"=="skip" goto :done

:: Build a timestamp using WMIC (reliable on all Windows versions)
for /f "tokens=2 delims==" %%I in ('wmic os get localdatetime /value 2^>nul') do set "_dt=%%I"
set "STAMP=!_dt:~0,8!_!_dt:~8,4!"

set "RELEASE_NAME=%PROJECT%_!DESC!_!STAMP!.rbf"

if not exist releases mkdir releases
copy "output_files\%PROJECT%.rbf" "releases\!RELEASE_NAME!" >nul
echo Released to: releases\!RELEASE_NAME!

:done

:: ---- Optional GitHub Push ----
::      Set environment variable AUTOPUSH=1 to enable:
::      > set AUTOPUSH=1
::      > compile.bat "my changes"
if "%AUTOPUSH%"=="1" (
    echo.
    echo [Git] Pushing to GitHub...
    git push origin main
    if %errorlevel% neq 0 (
        echo [Git] WARNING: Push failed. Check network connection or branch name.
    ) else (
        echo [Git] Pushed successfully to GitHub
    )
)

echo.
echo Done.
