`timescale 1ns/1ps

// tb_yuv_to_rgb_stream.v — streaming testbench for yuv_to_rgb.sv
//
// Reads sim/video_vectors.txt (generated by gen_vectors.py).
// Feeds one pixel per clock, checks every output against the reference.
//
// Run:
//   python3 sim/gen_vectors.py [optional_video.mp4]
//   iverilog -g2012 -o sim/tb_stream.vvp sim/tb_yuv_to_rgb_stream.v rtl/yuv_to_rgb.sv
//   vvp sim/tb_stream.vvp

module tb_yuv_to_rgb_stream;

localparam MAX_VECS = 2048;

// ── DUT ───────────────────────────────────────────────────────────────────────
reg        clk = 1'b0;
reg        reset = 1'b1;
reg  [7:0] Y = 8'd16, U = 8'd128, V = 8'd128;
reg        data_valid_in = 1'b0;
wire [15:0] rgb565;
wire        data_valid_out;

always #5 clk = ~clk;   // 100 MHz

yuv_to_rgb dut (
    .clk           (clk),
    .reset         (reset),
    .Y             (Y),
    .U             (U),
    .V             (V),
    .data_valid_in (data_valid_in),
    .rgb565        (rgb565),
    .data_valid_out(data_valid_out)
);

// ── Vector storage ────────────────────────────────────────────────────────────
reg  [7:0] y_arr  [0:MAX_VECS-1];
reg  [7:0] u_arr  [0:MAX_VECS-1];
reg  [7:0] v_arr  [0:MAX_VECS-1];
reg [15:0] exp_arr[0:MAX_VECS-1];
integer    vec_count;

// ── Shared counters (only written by check process) ───────────────────────────
integer pass_cnt, fail_cnt, check_i;
integer feed_i;

// ── Process 1: load vectors, reset, feed pixels ───────────────────────────────
integer fp, r;
initial begin
    // Load vectors from file
    vec_count = 0;
    fp = $fopen("sim/video_vectors.txt", "r");
    if (fp == 0) begin
        $display("ERROR: cannot open sim/video_vectors.txt");
        $display("       Run:  python3 sim/gen_vectors.py  first");
        $finish;
    end
    r = 4;
    while (r == 4 && vec_count < MAX_VECS) begin
        r = $fscanf(fp, " %h %h %h %h",
                    y_arr[vec_count], u_arr[vec_count],
                    v_arr[vec_count], exp_arr[vec_count]);
        if (r == 4) vec_count = vec_count + 1;
    end
    $fclose(fp);
    if (vec_count == 0) begin
        $display("ERROR: no vectors loaded (check file format)");
        $finish;
    end
    $display("Loaded %0d test vectors from sim/video_vectors.txt", vec_count);

    // Release reset
    repeat(3) @(posedge clk);
    @(negedge clk); reset = 1'b0;
    @(negedge clk);   // one idle cycle before first pixel

    // Stream all pixels — one per clock
    for (feed_i = 0; feed_i < vec_count; feed_i = feed_i + 1) begin
        @(negedge clk);
        Y = y_arr[feed_i];
        U = u_arr[feed_i];
        V = v_arr[feed_i];
        data_valid_in = 1'b1;
    end

    // De-assert after last pixel
    @(negedge clk);
    data_valid_in = 1'b0;
    Y = 8'd16; U = 8'd128; V = 8'd128;

    // Wait for pipeline to drain (latency ≤ 6 clocks + margin)
    repeat(12) @(posedge clk);

    // Final report
    $display("");
    $display("Results: %0d passed, %0d failed  (out of %0d vectors)",
             pass_cnt, fail_cnt, vec_count);
    if (fail_cnt == 0)
        $display("ALL PASS");
    else
        $display("FAILURES DETECTED");
    $finish;
end

// ── Process 2: check outputs as they arrive ───────────────────────────────────
// Runs concurrently with process 1. Uses level detection at posedge clk so
// back-to-back data_valid_out=1 cycles are all caught (unlike @posedge event).
initial begin
    pass_cnt = 0; fail_cnt = 0; check_i = 0;
    forever begin
        @(posedge clk); #1;   // sample after registered outputs have settled
        if (data_valid_out && check_i < vec_count) begin
            if (rgb565 !== exp_arr[check_i]) begin
                $display("FAIL [%4d] Y=%3d U=%3d V=%3d  got=0x%04X  exp=0x%04X",
                         check_i,
                         y_arr[check_i], u_arr[check_i], v_arr[check_i],
                         rgb565, exp_arr[check_i]);
                fail_cnt = fail_cnt + 1;
            end else begin
                pass_cnt = pass_cnt + 1;
            end
            check_i = check_i + 1;
        end
    end
end

// ── Safety watchdog ───────────────────────────────────────────────────────────
initial begin
    #5000000;
    $display("WATCHDOG TIMEOUT — simulation hung");
    $finish;
end

endmodule
